### ISSUE TITLE
1.0.0-beta.11 is incorrectly not a valid version

### ISSUE THREAD

**Issue by doozMen** [sersoft-gmbh/semver#107]
The .11 is the problem. When you change it to +11 it works. But as I read the specs it should allow .11. Another lib does it correctly `.package(url: "https://github.com/mrackwitz/Version.git", from: "0.8.0")`

**Comment by ffried** [comment]
Good find!

I misread the important part about 'dot-separated` in [the spec for prerelease identifiers](https://semver.org/#spec-item-9).
