### ISSUE TITLE
Warning for not enabling: SemVerMacrosPlugin

### ISSUE THREAD

**Issue by ErikLuimes** [sersoft-gmbh/semver#123]
Hi, We don't want to use the xcode plugin. Is it possible to disable it?
We keep getting the following warning. Thanks in advance.

![Screenshot 2024-04-11 at 15 12 04](https://github.com/sersoft-gmbh/semver/assets/7758763/f5380735-cafb-4100-9aeb-1909a4f9ce15)

**Comment by ffried** [comment]
This package has two products: `SemVer` and `SemVerMacros`. Only the latter links the macros plugin as dependency. So as long as you only use the `SemVer` product, Xcode _should_ not build / use the plugin. However, that's up to Xcode. As far as I know, we cannot do much more than separating the products.
So I'm afraid this might be an Xcode bug here.
